Blockly.Msg["MLPLAY_GAME_STATUS_OPTIONS"] = [
  ["%{BKY_TEMPLATE_GAME_STATUS_1}", "STATUS_1"],
  ["%{BKY_TEMPLATE_GAME_STATUS_2}", "STATUS_2"]
];
Blockly.Msg["MLPLAY_GET_INFO_OPTIONS"] = [
  ["%{BKY_TEMPLATE_SCENE_INFO_1}", "INFO_1"],
  ["%{BKY_TEMPLATE_SCENE_INFO_2}", "INFO_2"]
];
Blockly.Msg["MLPLAY_GET_CONSTANT_OPTIONS"] = [
  ["%{BKY_TEMPLATE_CONSTANT_1}", "1/0"],
  ["%{BKY_TEMPLATE_CONSTANT_2}", "2/100"]
];
Blockly.Msg["MLPLAY_RETURN_ACTION_OPTIONS"] = [
  ["%{BKY_TEMPLATE_ACTION_1}", "ACTION_1"],
  ["%{BKY_TEMPLATE_ACTION_2}", "ACTION_2"]
];
