var MSG = {
  title: "Blockly",
  blocks: "Blocks",
  lang: "Language",
  options: "Options",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  discard: "Discard all blocks",
  download: "Save Python file",
  runMLGame: "Play game",
  runPython: "Run Python file",
  openXml: "Open XML file",
  downloadXml: "Save XML file",
  en: "English",
  zh_hant: "Chinese",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catDicts: "Dictionaries",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  catFile: "File",
  catModel: "Model",
  listVariable: "list",
  textVariable: "text",
  dictVariable: "dictionary",
  modelVariable: "model",
  objVariable: "object",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML."
};
