var MSG = {
  title: "積木程式",
  blocks: "積木",
  examples: "範例程式",
  lang: "語言",
  options: "選項",
  linkTooltip: "儲存積木組並提供連結。",
  runTooltip: "於工作區中執行積木組所定義的程式。",
  badCode: "程式錯誤：\n%1",
  timeout: "超過最大執行數。",
  discard: "捨棄所有積木",
  download: "儲存 Python 檔",
  runMLGame: "玩遊戲",
  runPython: "執行 Python 檔",
  openXml: "開啟 XML 檔",
  openPython: "開啟 Python 檔",
  downloadXml: "儲存 XML 檔",
  en: "英文",
  zh_hant: "中文",
  catLogic: "邏輯",
  catLoops: "迴圈",
  catMath: "數學式",
  catText: "文字",
  catLists: "清單",
  catDicts: "字典",
  catNdarrays: "多維陣列",
  catColour: "顏色",
  catFile: "檔案",
  catPlot: "繪圖",
  catModel: "模型",
  catVariables: "變數",
  catFunctions: "函式",
  listVariable: "清單",
  ndarrayVariable: "多維陣列",
  textVariable: "文字",
  dictVariable: "字典",
  modelVariable: "模型",
  objVariable: "物件",
  filename: "檔案名稱",
  trainData: "訓練資料",
  testData: "測試資料",
  trainTarget: "訓練目標",
  testTarget: "測試目標",
  httpRequestError: "命令出現錯誤。",
  linkAlert: "透過此連結分享您的積木組：\n\n%1",
  hashError: "對不起，「%1」並未對應任何已保存的程式。",
  xmlError: "未能載入您保存的檔案。或許它是由其他版本的Blockly創建？",
  badXml: "解析 XML 時出現錯誤：\n%1\n\n選擇'確定'以放棄您的更改，或選擇'取消'以進一步編輯 XML。"
};
